import nodemailer from "nodemailer";
import { prisma } from "./prisma";

function istanbulNow(){const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul",year:"numeric",month:"2-digit",day:"2-digit",weekday:"short",hour:"2-digit",hourCycle:"h23"}).formatToParts(new Date());const value=(type:string)=>parts.find(part=>part.type===type)?.value||"";return {date:`${value("year")}-${value("month")}-${value("day")}`,weekday:value("weekday"),hour:Number(value("hour"))}}

export async function sendWeekdayReminders(){
  const now=istanbulNow();const sendHour=Number(process.env.REMINDER_SEND_HOUR||9);if(["Sat","Sun"].includes(now.weekday)||now.hour<sendHour)return {sent:0,skipped:true};
  const recipients=(process.env.REMINDER_EMAILS||"").split(",").map(value=>value.trim().toLowerCase()).filter(Boolean);if(!recipients.length||!process.env.SMTP_HOST||!process.env.SMTP_USER||!process.env.SMTP_PASS)return {sent:0,skipped:true};
  const day=new Date(`${now.date}T00:00:00.000Z`);const transporter=nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:process.env.SMTP_SECURE==="true",auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}});let sent=0;
  for(const recipient of recipients){if(await prisma.reminderEmailLog.findUnique({where:{recipient_day:{recipient,day}}}))continue;await transporter.sendMail({from:process.env.REMINDER_FROM||process.env.SMTP_USER,to:recipient,subject:"Günaydın! Bugünün yorumlarını birlikte karşılayalım 🌞",html:`<!doctype html><html><body style="margin:0;background:#f5f3ff;font-family:Arial,sans-serif;color:#1e1b4b"><table role="presentation" width="100%"><tr><td align="center" style="padding:32px 16px"><table role="presentation" width="600" style="max-width:600px;background:#fff;border-radius:20px;overflow:hidden;box-shadow:0 12px 35px rgba(76,29,149,.12)"><tr><td style="padding:32px;background:linear-gradient(135deg,#7c3aed,#4f46e5);color:#fff"><div style="font-size:13px;letter-spacing:2px;font-weight:bold">YORUMPULSE BETA</div><h1 style="margin:12px 0 0;font-size:28px">Günaydın! Güzel bir gün bizi bekliyor ✨</h1></td></tr><tr><td style="padding:32px"><p style="font-size:17px;line-height:1.7;margin-top:0">Bugün topluluğumuzla küçük ama değerli bir bağ kurmayı unutmayalım.</p><div style="padding:20px;border-radius:14px;background:#f5f3ff;border-left:4px solid #7c3aed"><strong>YouTube ve Facebook yorumlarını kontrol et, bekleyen cevapları tamamla ve izleyicilerimize seslerini duyduğumuzu hissettir.</strong></div><p style="font-size:15px;line-height:1.7;color:#64748b">Nazik bir cevap bazen bir izleyiciyi sadık bir topluluk üyesine dönüştürür. Bugün de harika bir iletişim günü olsun!</p><a href="${process.env.NEXT_PUBLIC_APP_URL||"https://wediacorpyorumpulse.vercel.app"}/gorevler" style="display:inline-block;margin-top:8px;padding:13px 22px;border-radius:12px;background:#7c3aed;color:#fff;text-decoration:none;font-weight:bold">Bugünkü görevlerimi aç</a></td></tr><tr><td style="padding:20px 32px;background:#fafafa;color:#94a3b8;font-size:12px">YorumPulse Community OS · Otomatik hafta içi hatırlatması</td></tr></table></td></tr></table></body></html>`});await prisma.reminderEmailLog.create({data:{recipient,day}});sent++}
  return {sent,skipped:false};
}
