import { prisma } from "./prisma";
import { logger } from "./logger";
const BASE="https://www.googleapis.com/youtube/v3";
async function quota(units:number){const day=new Date();day.setUTCHours(0,0,0,0);const row=await prisma.apiQuotaUsage.upsert({where:{service_day:{service:"youtube",day}},create:{service:"youtube",day,units,limit:10000},update:{units:{increment:units}}});if(row.units>row.limit*0.95)throw new Error("YouTube günlük API kotası güvenlik sınırına ulaştı.")}
async function request<T>(path:string,params:Record<string,string>,units=1):Promise<T>{const key=process.env.YOUTUBE_API_KEY;if(!key)throw new Error("YOUTUBE_API_KEY tanımlı değil.");await quota(units);const url=new URL(`${BASE}/${path}`);Object.entries({...params,key}).forEach(([k,v])=>url.searchParams.set(k,v));const res=await fetch(url,{next:{revalidate:0}});if(!res.ok){const text=await res.text();logger.error("youtube_api_error",{status:res.status,path,body:text.slice(0,300)});throw new Error(`YouTube API hatası (${res.status})`)}return res.json() as Promise<T>}
export async function resolveChannelId(input:string){const url=new URL(input.startsWith("http")?input:`https://youtube.com/${input}`);const direct=url.pathname.match(/\/channel\/(UC[\w-]+)/)?.[1];if(direct)return direct;const handle=url.pathname.match(/\/@([^/]+)/)?.[1];if(handle){const r=await request<{items?:{id:string}[]}>("channels",{part:"id",forHandle:handle});return r.items?.[0]?.id}const username=url.pathname.match(/\/(?:user|c)\/([^/]+)/)?.[1];if(username){const r=await request<{items?:{id:string}[]}>("channels",{part:"id",forUsername:username});return r.items?.[0]?.id}throw new Error("YouTube kanal bağlantısından kanal kimliği çözülemedi.")}
export async function fetchChannel(channelId:string){return request<{items:{id:string,snippet:{title:string,description:string,thumbnails:{high:{url:string}}},statistics:{subscriberCount:string,viewCount:string,videoCount:string},contentDetails:{relatedPlaylists:{uploads:string}}}[]}>("channels",{part:"snippet,statistics,contentDetails",id:channelId})}
export async function fetchPlaylistVideos(playlistId:string,pageToken?:string){return request<{nextPageToken?:string,items:{snippet:{resourceId:{videoId:string},title:string,description:string,publishedAt:string,thumbnails?:{high?:{url:string}}}}[]}>("playlistItems",{part:"snippet",playlistId,maxResults:"50",...(pageToken?{pageToken}:{})})}
export async function fetchVideoStats(ids:string[]){return request<{items:{id:string,statistics:{viewCount?:string,likeCount?:string,commentCount?:string}}[]}>("videos",{part:"statistics",id:ids.join(",")})}
export async function fetchComments(videoId:string,pageToken?:string){return request<{nextPageToken?:string,items:{id:string,snippet:{topLevelComment:{id:string,snippet:{textDisplay:string,authorDisplayName:string,authorChannelId?:{value:string},likeCount:number,publishedAt:string,updatedAt:string}}}}[]}>("commentThreads",{part:"snippet",videoId,maxResults:"100",textFormat:"plainText",order:"time",...(pageToken?{pageToken}:{})})}

