import { CheckCircle2, Circle, Clock3, ExternalLink } from "lucide-react";
import { prisma } from "@/lib/prisma";

const groups = [{ status: "TODO" as const, label: "Yapılacak", icon: Circle }, { status: "IN_PROGRESS" as const, label: "Devam ediyor", icon: Clock3 }, { status: "DONE" as const, label: "Tamamlandı", icon: CheckCircle2 }];

export default async function TasksPage() {
  const tasks = await prisma.task.findMany({ orderBy: [{ priority: "desc" }, { createdAt: "desc" }], include: { assignee: { select: { name: true } }, channel: { select: { name: true, versionChannel: true } }, comment: { select: { platform: true, permalinkUrl: true, video: { select: { title: true, permalinkUrl: true } } } } } });
  return <div className="mx-auto max-w-[1500px] space-y-6"><div><h1 className="text-3xl font-black">Görevler</h1><p className="mt-1 text-sm text-slate-500">YouTube ve Facebook yorumlarından otomatik oluşturulan iletişim görevleri.</p></div><div className="grid gap-5 lg:grid-cols-3">{groups.map(group => { const rows = tasks.filter(task => task.status === group.status); return <section key={group.status}><div className="mb-3 flex items-center gap-2"><group.icon size={17}/><h2 className="font-bold">{group.label}</h2><span className="tag bg-muted">{rows.length}</span></div><div className="space-y-3">{rows.map(task => { const link = task.comment?.permalinkUrl || task.comment?.video.permalinkUrl; return <article className="card p-4" key={task.id}><div className="flex flex-wrap items-center gap-2">{task.comment && <span className={`tag ${task.comment.platform === "FACEBOOK" ? "bg-blue-50 text-blue-700" : "bg-red-50 text-red-700"}`}>{task.comment.platform === "FACEBOOK" ? "Facebook" : "YouTube"}</span>}<span className={`tag ${task.priority === "HIGH" || task.priority === "CRITICAL" ? "bg-red-50 text-red-700" : "bg-muted"}`}>{task.priority}</span></div><h3 className="mt-3 font-bold">{task.title}</h3>{task.comment?.video.title && <p className="mt-1 text-xs font-semibold text-slate-500">Video: {task.comment.video.title}</p>}{task.description && <p className="mt-2 whitespace-pre-line text-sm text-slate-500">{task.description}</p>}{link && <a href={link} target="_blank" rel="noreferrer" className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-violet-600">Yoruma git <ExternalLink size={12}/></a>}<div className="mt-4 flex justify-between border-t pt-3 text-xs text-slate-400"><span>{task.assignee?.name || "Atanmadı"}</span><span>{task.channel?.versionChannel || task.channel?.name || task.priority}</span></div></article>; })}{!rows.length && <div className="rounded-xl border border-dashed p-8 text-center text-xs text-slate-400">Görev yok</div>}</div></section>; })}</div></div>;
}
