"use client";
import Link from "next/link";
import { Bot, Eye, EyeOff, LockKeyhole, Mail } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function LoginPage(){
  const [show,setShow]=useState(false); const [loading,setLoading]=useState(false);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);const form=new FormData(event.currentTarget);try{const response=await fetch("/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email:form.get("email"),password:form.get("password")})});const data=await response.json();if(response.ok)location.href="/";else toast.error(data.error)}finally{setLoading(false)}}
  return <main className="relative grid min-h-screen place-items-center overflow-hidden bg-slate-950 p-4 text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_15%_10%,#7c3aed44,transparent_32%),radial-gradient(circle_at_85%_90%,#0891b233,transparent_32%)]"/><section className="relative w-full max-w-md rounded-3xl border border-white/10 bg-white/[.07] p-8 shadow-2xl backdrop-blur-xl"><div className="mb-8 flex items-center gap-3"><span className="grid size-12 place-items-center rounded-2xl bg-gradient-to-br from-violet-500 to-indigo-600"><Bot/></span><div><h1 className="text-xl font-black">YorumPulse</h1><p className="text-[10px] font-bold uppercase tracking-[.2em] text-violet-300">Community OS</p></div></div><h2 className="text-3xl font-black">Hoş geldiniz</h2><p className="mt-2 text-sm text-slate-400">Kanal operasyon merkezinize güvenli giriş yapın.</p><form className="mt-7 space-y-4" onSubmit={submit}><label className="block"><span className="text-xs font-bold text-slate-300">E-posta</span><div className="relative mt-2"><Mail className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" size={17}/><input name="email" type="email" autoComplete="email" required className="h-12 w-full rounded-xl border border-white/10 bg-white/5 pl-10 pr-4 outline-none focus:border-violet-500"/></div></label><label className="block"><span className="text-xs font-bold text-slate-300">Parola</span><div className="relative mt-2"><LockKeyhole className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" size={17}/><input name="password" type={show?"text":"password"} autoComplete="current-password" required className="h-12 w-full rounded-xl border border-white/10 bg-white/5 pl-10 pr-11 outline-none focus:border-violet-500"/><button type="button" onClick={()=>setShow(!show)} className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-500">{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label><button disabled={loading} className="btn-primary h-12 w-full">{loading?"Giriş yapılıyor...":"Giriş yap"}</button></form><div className="mt-6 border-t border-white/10 pt-5 text-center text-xs text-slate-500">İlk kez mi kuruyorsunuz? <Link href="/setup" className="font-bold text-violet-300 hover:text-violet-200">İlk yöneticiyi oluşturun</Link></div></section></main>;
}
