"use client";
import { CheckCircle2,Circle,Clock3,ExternalLink,PlayCircle } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

type TaskRow={id:string;title:string;description:string|null;status:string;priority:string;dueAt:string|null;createdAt:string;updatedAt:string;assignee:{name:string}|null;channel:{name:string;versionChannel:string|null}|null;comment:{platform:"YOUTUBE"|"FACEBOOK";permalinkUrl:string|null;video:{title:string;permalinkUrl:string|null}}|null};
const groups=[{status:"TODO",label:"Yapılacak",icon:Circle},{status:"IN_PROGRESS",label:"Devam ediyor",icon:Clock3},{status:"DONE",label:"Tamamlandı",icon:CheckCircle2}];

export function TaskBoard({initialTasks}:{initialTasks:TaskRow[]}){
  const [tasks,setTasks]=useState(initialTasks);const [loading,setLoading]=useState<string|null>(null);
  async function update(id:string,status:"IN_PROGRESS"|"DONE"){
    setLoading(id);const response=await fetch(`/api/tasks/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({status})});const data=await response.json();if(response.ok){setTasks(rows=>rows.map(task=>task.id===id?{...task,status}:task));toast.success(status==="DONE"?"Görev tamamlandı":"Görev üzerinde çalışılıyor")}else toast.error(data.error);setLoading(null);
  }
  return <div className="mx-auto max-w-[1500px] space-y-6"><div><h1 className="text-3xl font-black">Görevler</h1><p className="mt-1 text-sm text-slate-500">Size atanmış YouTube ve Facebook iletişim görevleri.</p></div><div className="grid gap-5 lg:grid-cols-3">{groups.map(group=>{const rows=tasks.filter(task=>task.status===group.status);return <section key={group.status}><div className="mb-3 flex items-center gap-2"><group.icon size={17}/><h2 className="font-bold">{group.label}</h2><span className="tag bg-muted">{rows.length}</span></div><div className="space-y-3">{rows.map(task=>{const link=task.comment?.permalinkUrl||task.comment?.video.permalinkUrl;return <article className="card p-4" key={task.id}><div className="flex flex-wrap gap-2">{task.comment&&<span className={`tag ${task.comment.platform==="FACEBOOK"?"bg-blue-50 text-blue-700":"bg-red-50 text-red-700"}`}>{task.comment.platform==="FACEBOOK"?"Facebook":"YouTube"}</span>}<span className={`tag ${task.priority==="HIGH"||task.priority==="CRITICAL"?"bg-red-50 text-red-700":"bg-muted"}`}>{task.priority}</span></div><h3 className="mt-3 font-bold">{task.title}</h3>{task.comment?.video.title&&<p className="mt-1 text-xs font-semibold text-slate-500">Video: {task.comment.video.title}</p>}{task.description&&<p className="mt-2 line-clamp-6 whitespace-pre-line text-sm text-slate-500">{task.description}</p>}<div className="mt-3 flex flex-wrap gap-2">{link&&<a href={link} target="_blank" rel="noreferrer" className="btn-outline h-8 px-3 text-xs">Yoruma git <ExternalLink size={12}/></a>}{task.status==="TODO"&&<button disabled={loading===task.id} onClick={()=>update(task.id,"IN_PROGRESS")} className="btn-outline h-8 px-3 text-xs"><PlayCircle size={13}/>Yaptım / Başladım</button>}{task.status!=="DONE"&&<button disabled={loading===task.id} onClick={()=>update(task.id,"DONE")} className="btn-primary h-8 px-3 text-xs"><CheckCircle2 size={13}/>Tamamlandı</button>}</div><div className="mt-4 flex justify-between border-t pt-3 text-xs text-slate-400"><span>{task.assignee?.name||"Atanmadı"}</span><span>{task.channel?.versionChannel||task.channel?.name||task.priority}</span></div></article>})}{!rows.length&&<div className="rounded-xl border border-dashed p-8 text-center text-xs text-slate-400">Görev yok</div>}</div></section>})}</div></div>;
}
