import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft,ExternalLink } from "lucide-react";
import { channelAccessWhere,getSession,teamScopeWhere } from "@/lib/auth";
import { prisma } from "@/lib/prisma";
import { compactNumber } from "@/lib/utils";
import { platformLabel, platformTagClass } from "@/lib/platform";
import { EmptyState } from "@/components/empty-state";
import { ChannelResponsible } from "@/components/channel-responsible";

export default async function ChannelDetail({params}:{params:Promise<{id:string}>}){
  const {id}=await params;const session=await getSession();const channel=await prisma.channel.findFirst({where:{AND:[{id},channelAccessWhere(session)]},include:{videos:{take:20,orderBy:{publishedAt:"desc"}},alerts:{take:5,orderBy:{createdAt:"desc"}}}});if(!channel)notFound();
  // Sorumluyu yalnızca admin ya da kanalın kendi ekip lideri değiştirebilir.
  const canReassign=session?.role==="ADMIN"||(session?.role==="MANAGER"&&channel.teamLeadId===session.sub);
  const teamMembers=canReassign?await prisma.user.findMany({where:{AND:[teamScopeWhere(session),{role:{not:"ADMIN"}}]},orderBy:{name:"asc"},take:200,select:{id:true,name:true}}):[];
  return <div className="mx-auto max-w-[1300px] space-y-6"><Link href="/kanallar" className="inline-flex items-center gap-2 text-sm text-slate-500"><ArrowLeft size={16}/>Kanallara dön</Link><section className="card p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-black">{channel.versionChannel||channel.name}</h1><p className="mt-1 text-sm text-slate-500">{channel.category||"Kategori yok"} · {channel.status}</p></div><div className="flex gap-2">{channel.youtubeUrl&&<a className="btn-primary" href={channel.youtubeUrl} target="_blank" rel="noreferrer">YouTube <ExternalLink size={16}/></a>}{channel.facebookUrl&&<a className="btn-outline" href={channel.facebookUrl} target="_blank" rel="noreferrer">Facebook <ExternalLink size={16}/></a>}</div></div><div className="mt-6 grid gap-3 sm:grid-cols-4">{[["Abone",compactNumber(Number(channel.subscriberCount))],["İzlenme",compactNumber(Number(channel.totalViewCount))],["Video",channel.videoCount],["Yorum",channel.commentCount]].map(item=><div className="rounded-xl bg-muted p-4" key={String(item[0])}><b className="text-xl">{item[1]}</b><p className="text-xs text-slate-500">{item[0]}</p></div>)}</div></section><div className="grid gap-5 xl:grid-cols-2"><section className="card p-6"><h2 className="font-bold">Son videolar</h2>{channel.videos.length?<div className="mt-4 space-y-3">{channel.videos.map(video=><div className="border-b pb-3 last:border-0" key={video.id}><div className="flex justify-between gap-3"><b className="text-sm">{video.title}</b><span className={`tag ${platformTagClass(video.platform)}`}>{platformLabel(video.platform)}</span></div><p className="text-xs text-slate-400">{video.publishedAt.toLocaleDateString("tr-TR")} · {video.commentCount} yorum</p></div>)}</div>:<EmptyState size="sm" title="Video henüz senkronize edilmedi."/>}</section><section className="card p-6"><h2 className="font-bold">Kanal bilgileri</h2><dl className="mt-4 space-y-3 text-sm"><div className="flex items-center justify-between gap-4 border-b pb-3"><dt className="text-slate-400">Sorumlu</dt><dd className="text-right font-medium">{canReassign?<ChannelResponsible channelId={channel.id} responsibleId={channel.responsibleId} teamMembers={teamMembers}/>:channel.responsibleName||"—"}</dd></div>{[["CMS",channel.cms],["Versiyon",channel.versionChannel],["Ekip lideri",channel.teamLeadName],["UC",channel.uc]].map(([key,value])=><div className="flex justify-between gap-4 border-b pb-3" key={key}><dt className="text-slate-400">{key}</dt><dd className="text-right font-medium">{value||"—"}</dd></div>)}</dl></section></div></div>;
}
